# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    # libraries
    #| context: setup
    import seaborn as sns
    from shiny import reactive
    from shiny.express import render, ui
    from IPython.display import display, Markdown

    # ========================================================================

    ui.input_select('x', 'Entidad Federativa',
      choices=[
        'Aguascalientes','Baja California','Baja California Sur','Campeche',
        'Chiapas','Chihuahua','Ciudad de México','Coahuila',
        'Colima','Durango','México','Guanajuato',
        'Guerrero','Hidalgo','Jalisco','Michoacán',
        'Morelos','Nayarit','Nuevo León','Oaxaca',
        'Puebla','Querétaro','Quintana Roo','San Luis Potosí',
        'Sinaloa','Sonora','Tabasco','Tamaulipas',
        'Tlaxcala','Veracruz','Yucatán','Zacatecas',
        ]
      )

    # ========================================================================

    dict(
      value = "29"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = "95"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = " 5 de 12"
    )

    # ========================================================================

    dict(
      value = "2"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = "6 de 12"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = "6,546"
    )

    # ========================================================================

    dict(
      value = 56
    )

    # ========================================================================

    dict(
      value = 25
    )

    # ========================================================================

    dict(
      color = "primary",
      value = 16
    )

    # ========================================================================

    dict(
      value = "250,000"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = "1.2"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = "65,000,000"
    )

    # ========================================================================

    dict(
      color = "primary",
      value = "15,000"
    )

    # ========================================================================



    return None


_static_assets = ["tablero_files","images/portada.png","images/prestaciones2.svg","images/sueldo.svg","images/aportaciones_subprograma.svg","images/funciones.svg","images/rfid.svg","images/capacitacion_cursos.svg","images/salarios_ordenado.svg","images/aportaciones_federales_por_entidad_mapa.svg","images/sesnsp.png","tablero_files/libs/quarto-html/tippy.css","tablero_files/libs/quarto-html/quarto-syntax-highlighting-b719d3d4935f2b08311a76135e2bf442.css","tablero_files/libs/quarto-html/quarto-syntax-highlighting-dark-c8b544e1eab81f7563542c0a8b71d1e9.css","tablero_files/libs/bootstrap/bootstrap-icons.css","tablero_files/libs/bootstrap/bootstrap-57fa414b915ca0d51f41cb565a059b40.min.css","tablero_files/libs/bootstrap/bootstrap-dark-cd70e9f35e31efa67545f5aa8e8bf657.min.css","tablero_files/libs/clipboard/clipboard.min.js","tablero_files/libs/quarto-html/quarto.js","tablero_files/libs/quarto-html/tabsets/tabsets.js","tablero_files/libs/quarto-html/popper.min.js","tablero_files/libs/quarto-html/tippy.umd.min.js","tablero_files/libs/quarto-html/anchor.min.js","tablero_files/libs/bootstrap/bootstrap.min.js","tablero_files/libs/quarto-dashboard/quarto-dashboard.js","tablero_files/libs/quarto-dashboard/stickythead.js","tablero_files/libs/quarto-dashboard/web-components.js","tablero_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "tablero.html",
    server,
    static_assets=_static_assets,
)
